adventureworks:
  target: postgres
  outputs:
    duckdb:
     type: duckdb
     path: target/adventureworks.duckdb
     threads: 12
    postgres:  
      type: postgres
      host: localhost
      user: data_engineer
      password: password
      port: 5432
      dbname: data_engineer
      schema: dbo
      threads: 12
